[metadata]
creation_date = "2021/10/11"
maturity = "development"
updated_date = "2021/10/11"

[rule]
name = "Ensure that the API server pod specification file ownership is set to root:root"
tags = [ "Elastic", "CIS" ]
interval = "5m"
enabled = true
description = "Ensure that the API server pod specification file ownership is set to root:root."
risk_score = 21
severity = "low"
license = ""
author = ["Elastic"]
false_positives = []
from = "now-360s"
rule_id = "6036c20c-c200-42e7-ae5c-fac6a8f89e89"
max_signals = 100
risk_score_mapping = []
severity_mapping = []
threat = []
to = "now"
references = []
exceptions_list = []
type = "eql"
language = "eql"
index = [ "logs*",]
query = '''
any where osquery.filename == "kube-apiserver.yaml" and (osquery.gid != 0 or osquery.uid != 0)
'''
filters = []
throttle = "no_actions"
actions = []
timestamp_override = "event.ingested"